// Generated by CoffeeScript 1.6.3
(function() {
  var errorLogs, fs, sysConfig;

  fs = require('fs');

  sysConfig = require('./config/sysConfig');

  errorLogs = {
    error: 0,
    warning: 0
  };

  exports.compile = function(file) {
    return console.log(file);
  };

}).call(this);
