// Generated by CoffeeScript 1.6.3
(function() {
  var CleanCSS, UglifyJS, fs, minify;

  fs = require('fs');

  UglifyJS = require("uglify-js");

  CleanCSS = require('clean-css');

  minify = {
    js: function(path) {
      return UglifyJS.minify(path).code;
    },
    css: function(path) {
      var code;
      code = fs.readFileSync(path, "utf8");
      code = code.replace(/\s/g, '');
      return new CleanCSS().minify(code);
    }
  };

  module.exports = function(path, type) {
    type = type.substring(1, type.length);
    return minify[type](path);
  };

}).call(this);
