// Generated by CoffeeScript 1.6.3
(function() {
  var fs;

  fs = require('fs');

  /*
  * mkdirSync
  * @param {String} folderPath 路径
  * @param {Number} mode 文件夹权限
  * @param {Function} callback 回调
  */


  exports.mkdirSync = function(folderPath, mode, callback) {
    var arr, inner, path;
    path = require("path");
    arr = folderPath.split("/");
    if (typeof mode === 'function') {
      callback = mode;
      mode = '0755';
    }
    if (arr[0] === ".") {
      arr.shift();
    }
    if (arr[0] === "..") {
      arr.splice(0, 2, arr[0] + "/" + arr[1]);
    }
    inner = function(cur) {
      if (!path.existsSync(cur)) {
        fs.mkdirSync(cur, mode);
      }
      if (arr.length) {
        return inner(cur + "/" + arr.shift());
      } else {
        return callback && callback();
      }
    };
    return arr.length && inner(arr.shift());
  };

}).call(this);
