// Generated by CoffeeScript 1.6.3
(function() {
  var DOT_RE, DOUBLE_DOT_RE, DOUBLE_SLASH_RE;

  DOT_RE = /\/\.\//g;

  DOUBLE_DOT_RE = /\/[^/]+\/\.\.\//;

  DOUBLE_SLASH_RE = /([^:/])\/\//g;

  module.exports = function(path) {
    path = path.replace(DOT_RE, "/");
    while (path.match(DOUBLE_DOT_RE)) {
      path = path.replace(DOUBLE_DOT_RE, "/");
    }
    path = path.replace(DOUBLE_SLASH_RE, "$1/");
    return path;
  };

}).call(this);
